version: '3'
services:
  agent:
    image: thanhtunguet/azure-devops-agent:latest
    env_file: .env
    restart: always
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
