name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag thanhtunguet/azure-devops-agent:latest
        eval `echo ${{secret.docker_password}}` | docker login --username ${{secret.docker_username}} --password-stdin
        docker push thanhtunguet/azure-devops-agent:latest
