name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{secret.docker_username}}
      DOCKER_PASSWORD: ${{secret.docker_password}}

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag thanhtunguet/azure-devops-agent:latest
        eval `echo ${DOCKER_PASSWORD}` | docker login --username ${DOCKER_USERNAME} --password-stdin
        docker push thanhtunguet/azure-devops-agent:latest
